### ISSUE TITLE
spacetime('9-1-2021').unixFmt('MMM') === 'Sept'

### ISSUE THREAD

**Issue by svey** [spencermountain/spacetime#304] opened 2021-09-01 16:31 UTC
The issue I'm seeing is `spacetime('9-1-2021').unixFmt('MMM') === 'Sept'`— unless I'm missing something, I believe this should be a 3 digit month. Same for `.format('month-short')` although if the ladder remains 4 digits I guess month short is subject to interpretation

**Comment by spencermountain** [comment] 2021-09-01 19:07
hey @svey - i'm confused what the issue is - is it the input format, or the 'MMM' output?
both seem valid to me, can you clarify
thanks

**Comment by svey** [comment] 2021-09-03 22:47
> hey @svey - i'm confused about what the issue is - is it the input format, or the 'MMM' output?
> both seem valid to me, can you clarify?
> thanks

Hey @spencermountain — sorry for the confusion. Every other library I've tried MMM unix formatting return a 3 characters month. Only on spacetime does this return 4 characters and it's only for September— our team only discovered this a few days ago when the month hit September and our testing suite is looking for 'Sep'. Just seems odd that MMM [Jan, Feb, Mar, Jun, Jul, Aug, Sept, Oct, Nov, Dec].

My suggestion would be let the unix format MMM default to Sep and let month-short be Sept. Hope that makes sense— and I really appreciate you taking the time to get back to me

**Comment by spencermountain** [comment] 2021-09-07 13:51
ahh, yeah. I agree. I don't know why it does 'Sept'. I've seen this too.
I will add this to the next release. Sorry about that. Agree we should return the same as the other libs here.
cheers

**Comment by svey** [comment] 2021-09-21 20:32
thanks @spencermountain !

**Comment by spencermountain** [comment] 2022-01-05 15:54
fixed in 7.0.0
cheers

**Closed by spencermountain** 2022-01-05 15:54 UTC
Labels: ready, next-release
