### ISSUE TITLE
[Typescript] Could not find declaration file for module 'spacetime' 

### ISSUE THREAD

**Issue by abetoots** [spencermountain/spacetime#356] opened 2022-12-07 02:17 UTC
Could not find declaration file for module 'spacetime' when using `moduleResolution: 'NodeNext'` or "Node16".

TS version: 4.9.3
Spacetime version: 7.2.0

**Comment by spencermountain** [comment] 2022-12-08 21:56
hey Abe, I may need more information about your build setup.
I'm afraid i'm not very sharp at typescript details. From what I understand, the typefile is linked in spacetime properly.
let me know if you have any suggestions
cheers

**Comment by the-sky-is-pink** [comment] 2023-04-05 10:37
Hey , is there any solution for this ?

**Comment by folkg** [comment] 2023-06-11 21:14
I'm having the same issue.

**Comment by spencermountain** [comment] 2023-06-12 15:21
hey @jecraig - you know anything about `nodeNext`?
happy to make any changes, would love some help.

**Comment by jecraig** [comment] 2023-06-17 00:17
@spencermountain Ok, so I don't have a fix for this, but it looks like it's just an issue with our package.json. Here's a demo that reproduces the issue.

https://github.com/jecraig/Spacetime356Test

I changed the package.json to this and it worked for the project, but your rollup failed to run.

`{
  "name": "spacetime",
  "version": "7.4.4",
  "description": "figure-out dates across timezones",
  "unpkg": "builds/spacetime.min.js",
  "main": "src/index.js",
  "module": "./src/index.js",
  "es2015": "./src/index.js",
  "types": "types/index.d.ts",
  "sideEffects": false,
  "exports": {
    ".": {
      "types": "./types/index.d.ts",
      "require": "./builds/spacetime.cjs",
      "default": "./src/index.js"
    }
  },
  "scripts": {
    "build": "npm run pack && npm run version && rollup -c --silent",
    "build:tz": "node ./scripts/updateZonefile.js",
    "pack": "node ./zonefile/pack.js",
    "version": "node ./scripts/version.js",
    "watch": "amble ./scratch.js",
    "test": "tape ./test/**/*.test.js | tap-dancer  --color always",
    "testb": "TESTENV=prod tape ./test/**/*.test.js | tap-dancer  --color always",
    "test:types": "ts-node ./test/types/index.ts | tap-dancer  --color always",
    "coverage": "nyc -r lcov -n 'src/**/*' -n 'plugins/**/*' npm run coverage:tests",
    "coverage:tests": "npm run test",
    "codecov": "npm run coverage && codecov -t 411de6c7-82d2-41e9-a1cc-9096cdab6c72",
    "lint": "eslint ./src --ext .js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/spencermountain/spacetime.git"
  },
  "files": [
    "src",
    "builds",
    "api",
    "types",
    "zonefile"
  ],
  "prettier": {
    "trailingComma": "none",
    "tabWidth": 2,
    "semi": false,
    "singleQuote": true,
    "printWidth": 100
  },
  "devDependencies": {
    "codecov": "3.8.3",
    "nyc": "^15.1.0",
    "rollup": "3.9.0",
    "rollup-plugin-commonjs": "10.1.0",
    "rollup-plugin-filesize-check": "0.0.1",
    "rollup-plugin-json": "^4.0.0",
    "rollup-plugin-node-resolve": "5.2.0",
    "rollup-plugin-terser": "7.0.2",
    "shelljs": "0.8.5",
    "tap-dancer": "0.3.4",
    "tape": "5.6.3",
    "timekeeper": "2.2.0",
    "amble": "^1.3.0"
  },
  "license": "Apache-2.0"
}`

I'll try playing with it more after the weekend, but this is what I've discovered so far.

**Comment by spencermountain** [comment] 2023-07-28 15:27
should be fixed now in `7.4.5` - let me know if you see any other funny business.
cheers

**Closed by spencermountain** 2023-07-28 15:27 UTC
Labels: hmm
