### ISSUE TITLE
Spacetime not working in MacOS Sonoma (Cannot find timezone named: 'cet'. Please enter an IANA timezone id)

### ISSUE THREAD

**Issue by trocoli96** [spencermountain/spacetime#397] opened 2023-08-21 13:48 UTC
When updating the OS to the new MacOS Sonoma (now in beta) the spacetime constructor fails because taking the browser timezone is not a IANA timezone. For example:

**In Europe:**

`Intl.DateTimeFormat().resolvedOptions().timeZone`

Before:
'Europe/Madrid'

Now:
'CET'

So this results on spacetime failing
![image](https://github.com/spencermountain/spacetime/assets/28953515/bae63c08-4a1f-473f-8739-a4369e8f53f6)

If this is happening on the OS level it may affect other regions in the world too.

**Comment by eaarranz** [comment] 2023-08-21 14:08
We may help you with the implementation if you consider that it should be fixed ;) Maybe you should allow the same approach that you use at timezones-soft in the lookupTz function

**Comment by spencermountain** [comment] 2023-08-22 14:00
oh my gosh - thank you for the heads-up.
Is this documented anywhere? Yeah, I'm happy to fix this asap.
Yep, at minimum we can add a guard to prevent the runtime error.
Please let me know if you can dig anything up, about this change. oof!
thank you.

**Comment by eaarranz** [comment] 2023-08-22 14:53
Since the heads up from one of our customers, we have been trying to reproduce it, and we were able to reproduce it with the last beta on one of our laptops. At least here where we were getting 'Europe/Madrid', we are getting 'cet'; configuring the timezone manually to 'Europe/Madrid' does not change it back to 'Europe/Madrid' and keeps returning 'cet.'.

We did not find any documentation regarding it...  But we are kind of lost on where Apple tracks these types of changes.

Since you have the aliases, maybe we can extend them to include `cet`, `met`, `eet` and `wet` and use them to check if the returned value of `Intl.DateTimeFormat().resolvedOptions().timeZone` is an alias and return the IANA value of them.

**Comment by spencermountain** [comment] 2023-08-22 14:59
thank you. Yup - I will release a hotfix this afternoon.
appreciate the help.

**Comment by eaarranz** [comment] 2023-08-22 15:04
I will open a bug to Apple as feedback for Sonoma; at least we'll know if it's something planned or needs fixing on their side.

**Comment by spencermountain** [comment] 2023-08-22 17:01
ok - released a fix for this as `7.4.7` - but would love some help testing it against any variants of this.

Yeah - turns-out there's even-weirder responses than 'CET' from the Intl api, apparently you can get the result `'Factory'`. No idea how, but it appears in:
```js
Intl.supportedValuesOf('timeZone')
```
I added [a test](https://github.com/spencermountain/spacetime/blob/master/test/intl.test.js) for the Node 18, and Firefox results, but I'm sure there's more to be found. I [aliased them](https://github.com/spencermountain/spacetime/blob/master/zonefile/aliases.js#L150) to whatever it said [in wikipedia](https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones). - but please let me know if I've done something foolish. There's always a good chance of this.
cheers

**Closed by spencermountain** 2023-08-22 17:01 UTC
Labels: next-release, priority

**Comment by eaarranz** [comment] 2023-08-22 21:00
I'll take a look at both the supported values that I get on Chrome and the values that we get on Sonoma.
