### ISSUE TITLE
[i18n] Allow for full customization of all hard-coded strings

### ISSUE THREAD

**Issue by jlmmns** [spencermountain/spacetime#145] opened 2019-06-07 12:03 UTC
As of now, only days and months can be customized.

It would be nice if we could customize all hard-coded strings, such as:

- units (seconds, minutes, hours, etc.)
- since (in, almost, ago, etc.)

**Comment by spencermountain** [comment] 2019-06-07 15:19
hey @jlmmns yeah you're right - what are you thinking about for i18n units, this?
```
spacetime.now().add(1, 'journée')
```

otherwise a dupe of [#110](https://github.com/spencermountain/spacetime/issues/110)

**Comment by jlmmns** [comment] 2019-06-07 18:46
@spencermountain Thanks for the quick follow-up! The API should stay English only, I'm sure.

I'm talking about the formatting. So, it's related to #110, indeed. But more than just the "ago" string.
Pretty much every hard-coded string that spacetime displays, should be customizable.

I'd want to try to contribute with a PR, but I don't have any time, unfortunately.

**Comment by spencermountain** [comment] 2019-08-07 16:28
merging with #110 
cheers

**Closed by spencermountain** 2019-08-07 16:28 UTC
