### ISSUE TITLE
next('day') function returns same day instead of next day

### ISSUE THREAD

**Issue by hybmg57** [spencermountain/spacetime#166] opened 2019-10-06 05:25 UTC
this happens after 6 October 2019 4am to 4.52am (AEST) time and every 0-52th minute every hour afterwards

**Comment by spencermountain** [comment] 2019-10-06 17:46
hey, thanks Jae.
I haven't been able to reproduce this, can you help?
This seems to work, for me:
```js
let s = spacetime('6 October 2019', 'australia/sydney').time('4:20am')
s.log()
s = s.add(1, 'day')
s.log()
```
cheers

**Comment by hybmg57** [comment] 2019-10-07 06:06
Its `.next('day')` function not `.add`

**Comment by spencermountain** [comment] 2019-10-08 13:54
ah, thanks. I've been able to reproduce this. It appears within a few hours of the dst change for this timezone - between 3am and 11pm.
```js
let s = spacetime('6 October 2019', 'australia/sydney').time('4:20am')
s.log()
s = s.startOf('day')
s.log()
```
for future me - in startOf('day'), `hour=0` walks back too far because of the dst change (expected) but the fallback behaviour fails to choose the correct date

**Comment by spencermountain** [comment] 2019-11-01 16:45
just took another look at this and it appears things are even worse now:
```js
spacetime('October 6th 2019', 'australia/sydney')  // Oct 5th
```
hmph.  This is the buggiest time of year for timezone math.

gonna flag this as a priority

**Comment by spencermountain** [comment] 2019-11-07 18:04
fixed in `6.3.0`.
cheers

**Closed by spencermountain** 2019-11-07 18:04 UTC
Labels: bug, next-release, priority
