### ISSUE TITLE
Incorrect date transition during DST

### ISSUE THREAD

**Issue by MomentumGuild** [spencermountain/spacetime#113] opened 2019-03-29 14:26 UTC
Right now, when constructing spacetime dates via and array of parts + a specific timezone, the date becomes incorrect if its the date of a dst change:

````
    const dts = spacetime([year, month - 1, date], 'Europe/Stockholm')
      .format('iso-utc');

    const s = spacetime([year, month - 1, date], 'Europe/Stockholm');
    const s2 = spacetime([year, month - 1, date - 1], 'Europe/Stockholm');
    const s3 = spacetime([year, month - 1, date - 1], 'Europe/Stockholm').add(1, 'days');

    console.log(
    console.log(year, month, date, s.date(), s2.date(), s3.date(), dts);
````

running the above code yields:

````
2019 3 31
s:  30
s2:  30
s3:  31
2019-03-29T23:00:00.000Z
````

**Comment by spencermountain** [comment] 2019-03-29 20:55
hi @MomentumGuild ya thanks for the report.
I think it's probably a dupe of [#106](https://github.com/spencermountain/spacetime/issues/106), but I'll check it out when I get a chance
cheers

**Comment by spencermountain** [comment] 2019-04-06 18:04
thanks, I reproduced this:
```js
const d = spacetime([2019, 2, 31], 'Europe/Stockholm')
console.log(d.format('nice'))
```
urghh

**Comment by olivergg** [comment] 2019-04-10 19:04
I also have another corner case :

```node
> spacetime(1554007020000, 'GMT').unixFmt('dd/MM/yyyy hh:mm:ss')
'31/03/2019 04:37:00'
> spacetime(1554007020000, 'America/Guadeloupe').unixFmt('dd/MM/yyyy HH:mm:ss')
'30/03/2019 23:37:00' // why ? America/Guadeloupe should be GMT-4, not GMT-5
> spacetime(1554007020000+86400000, 'America/Guadeloupe').unixFmt('dd/MM/yyyy HH:mm:ss')
'01/04/2019 00:37:00' // this is the expected result for the next day
// note that America/Guadeloupe does not use DST, but the machine on which I've run the code is in Europe with DST
```


The funny thing is that I've ended up finding this issue while debugging an old GWT application which has exactly the same issue in formating date in another timezone. FYI , here is the relevant GWT source code  https://github.com/gwtproject/gwt/blob/205b88a4d88cc0c23b2cd0df681a18d114443a7c/user/src/com/google/gwt/i18n/shared/DateTimeFormat.java#L761. Hope it can be useful ;)

**Comment by spencermountain** [comment] 2019-04-12 22:57
hey, think I've fixed these two issues.
```
spacetime(1554007020000, 'America/Guadeloupe').unixFmt('dd/MM/yyyy HH:mm:ss')
//31/03/2019 00:37:00
```
it's on dev now, will close this when **5.7.0** is released.
thanks for your help

**Comment by spencermountain** [comment] 2019-04-13 17:07
k, think i got this in `5.7.0`

**Closed by spencermountain** 2019-04-13 17:07 UTC
Labels: bug, fixed-on-dev, priority
