### ISSUE TITLE
Unexpected results near DST 2023 boundaries (Europe/Helsinki)

### ISSUE THREAD

**Issue by pulakkam** [spencermountain/spacetime#374] opened 2023-02-17 12:52 UTC
Hello,

I checked if there are any problems related to DST 2023 in `Europe/Helsinki` and there seem to be some.

My test code:
```
import spacetime from 'spacetime'

const isotimes = [
  '2023-03-26T00:30:00.000Z', // March 2023
  '2023-03-26T01:30:00.000Z',
  '2023-03-26T02:30:00.000Z',
  '2023-03-26T03:30:00.000Z',
  '2023-03-26T04:30:00.000Z',
  '2023-03-26T05:30:00.000Z',
  '2023-10-29T00:30:00.000Z', // October 2023
  '2023-10-29T01:30:00.000Z',
  '2023-10-29T02:30:00.000Z',
  '2023-10-29T03:30:00.000Z',
  '2023-10-29T04:30:00.000Z',
]

isotimes.forEach((isotime) => {
  const time = spacetime(isotime)
  console.log(isotime)
  console.log(time.format('iso'))
  console.log(time.goto('Europe/Helsinki').format('iso'))
  console.log()
})
```
Results:
```
2023-03-26T00:30:00.000Z
2023-03-26T00:30:00.000Z
2023-03-26T02:30:00.000+02:00

2023-03-26T01:30:00.000Z
2023-03-26T01:30:00.000Z
2023-03-26T05:30:00.000+03:00 // Expected: 2023-03-26T04:30:00.000+03:00

2023-03-26T02:30:00.000Z
2023-03-26T02:30:00.000Z
2023-03-26T06:30:00.000+03:00 // Expected: 2023-03-26T05:30:00.000+03:00

2023-03-26T03:30:00.000Z
2023-03-26T02:30:00.000Z      // Expected: 2023-03-26T03:30:00.000Z
2023-03-26T06:30:00.000+03:00

2023-03-26T04:30:00.000Z
2023-03-26T04:30:00.000Z
2023-03-26T07:30:00.000+03:00

2023-03-26T05:30:00.000Z
2023-03-26T05:30:00.000Z
2023-03-26T08:30:00.000+03:00

2023-10-29T00:30:00.000Z
2023-10-29T00:30:00.000Z
2023-10-29T03:30:00.000+03:00

2023-10-29T01:30:00.000Z
2023-10-29T00:30:00.000Z      // Expected: 2023-10-29T01:30:00.000Z
2023-10-29T03:30:00.000+03:00

2023-10-29T02:30:00.000Z
2023-10-29T02:30:00.000Z
2023-10-29T03:30:00.000+02:00 // Expected: 2023-10-29T04:30:00.000+02:00

2023-10-29T03:30:00.000Z
2023-10-29T03:30:00.000Z
2023-10-29T05:30:00.000+02:00

2023-10-29T04:30:00.000Z
2023-10-29T04:30:00.000Z
2023-10-29T06:30:00.000+02:00
```
Is there something I could do to get expected results?

Thank you.

**Comment by pulakkam** [comment] 2023-02-17 18:28
Actually the results are identical, no difference between my original code and your version.

**Comment by spencermountain** [comment] 2023-02-17 18:46
oof, sorry! lemme check it out after a good sleep.

**Comment by spencermountain** [comment] 2023-02-19 13:48
oh - yup, this is a dupe of #235 
sorry for my code-blindness yeterday
i'm working on a fix. it requires a re-write. Hope to have it ready in a couple weeks, atleast as a beta
thanks for your patience. the offsets will only be off by an hour, within an hour of a dst change
cheers

**Closed by spencermountain** 2023-02-19 13:48 UTC
Labels: bug, hmm
